Issue number: Obtained from: Submitted by: Reviewed by:  Rajesh Arcot *Synopsis*: JES:accessmanager:Wrong error message is displayed 1) Go http://server.domain/UI/Login?module=LDAP . 2) Log in as amadmin. 3) Go Realms -> root realm -> Authentication -> Module Instance -New 4) Select type 'Membership', and enter name ', .
See error message Such node does not exist in the directory server.
which is not correct.

Evaluation & fix :
The error ultimately comes when the new authentication instance is
attempted to be saved in sms. From the debug file amSMSLdap the
following exception is being thrown

ERROR: SMSLdapObject: Invalid
DN=ou=,",ou=default,ou=OrganizationConfig,ou=1.0,ou=iPlanetAMAuthMembershipService,ou=services,dc=sun,dc=com

1) Modified SMSLdapObject.java to log this as a warning message, instead
of error message.
2) Split the following check into two.


git-svn-id: https://svn.java.net/svn/opensso~svn/trunk@30 b2119f5d-607e-cfcf-c5d3-9fa3ed8061d4