Issue number: Obtained from: Submitted by:  Dennis Seah Reviewed by:   Rajesh Arcot
Log Message Provider class is generating error messages like this

> ERROR: LogMessageProviderBase.formatMessage: ATTEMPT_IDENTITY_CREATION
> mismatch in number of elements in string array with that is defined in
> message ID XML file
> ERROR: LogMessageProviderBase.formatMessage: POLICY_EVALUATION mismatch
> in number of elements in string array with that is defined in
> message ID
> XML file

This is because there is bug in LogMessageID.java that mis counted the
number of items in the datainfo XML element tag.


git-svn-id: https://svn.java.net/svn/opensso~svn/trunk@181 b2119f5d-607e-cfcf-c5d3-9fa3ed8061d4